### PR TITLE
Update Bank.java

### PR DESCRIPTION
**Pull request by ghost**
I propose this can you please assist me.

### CODE REVIEW

**Comment by ghost** [comment]
Just learning that's all

**Comment by ghost** [comment]
I think it's time for change.

**Comment by jbki** [comment]
So all you did was change the package name? yea go ahead I don't give a shit

**Comment by ghost** [comment]
> So all you did was change the package name? yea go ahead I don't give a shit

Ok thanks bro if it doesn't work please give me some pointers.

**Pull request merged**
